# Generated by Django 5.0.7 on 2025-11-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('n_mecanografico', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'aluno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnoCurricular',
            fields=[
                ('id_anocurricular', models.AutoField(primary_key=True, serialize=False)),
                ('ano_curricular', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ano_curricular',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnoLetivo',
            fields=[
                ('id_anoletivo', models.AutoField(primary_key=True, serialize=False)),
                ('anoletivo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ano_letivo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('grau', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_docente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'docente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('horario', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'horario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InscricaoTurno',
            fields=[
                ('id_inscricao', models.AutoField(primary_key=True, serialize=False)),
                ('id_unidadecurricular', models.IntegerField(blank=True, null=True)),
                ('data_inscricao', models.DateField()),
            ],
            options={
                'db_table': 'inscricao_turno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InscritoUc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'inscrito_uc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LecionaUc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'leciona_uc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id_matricula', models.AutoField(primary_key=True, serialize=False)),
                ('data_matricula', models.DateField()),
                ('estado', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'matricula',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id_semestre', models.AutoField(primary_key=True, serialize=False)),
                ('semestre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'semestre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('n_turno', models.IntegerField()),
                ('tipo', models.CharField(max_length=255)),
                ('capacidade', models.IntegerField()),
            ],
            options={
                'db_table': 'turno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TurnoUc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'turno_uc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadeCurricular',
            fields=[
                ('id_unidadecurricular', models.AutoField(primary_key=True, serialize=False)),
                ('ects', models.IntegerField()),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'unidade_curricular',
                'managed': False,
            },
        ),
    ]
