# Generated by Django 5.2.6 on 2025-11-06 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={},
        ),
        migrations.AlterModelOptions(
            name='anocurricular',
            options={},
        ),
        migrations.AlterModelOptions(
            name='anoletivo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={},
        ),
        migrations.AlterModelOptions(
            name='docente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='horario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='inscricaoturno',
            options={},
        ),
        migrations.AlterModelOptions(
            name='inscritouc',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lecionauc',
            options={},
        ),
        migrations.AlterModelOptions(
            name='matricula',
            options={},
        ),
        migrations.AlterModelOptions(
            name='semestre',
            options={},
        ),
        migrations.AlterModelOptions(
            name='turno',
            options={},
        ),
        migrations.AlterModelOptions(
            name='turnouc',
            options={},
        ),
        migrations.AlterModelOptions(
            name='unidadecurricular',
            options={},
        ),
    ]
