# Generated by Django 5.2.6 on 2025-11-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_aluno_options_alter_anocurricular_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunosMatriculadosPorDia',
            fields=[
                ('id_matricula', models.IntegerField(primary_key=True, serialize=False)),
                ('n_mecanografico', models.IntegerField()),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=50)),
                ('data_matricula', models.DateTimeField()),
                ('dia_matricula', models.DateField()),
                ('ano_matricula', models.IntegerField()),
            ],
            options={
                'db_table': 'vw_alunos_matriculados_por_dia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlunosPorOrdemAlfabetica',
            fields=[
                ('n_mecanografico', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('id_anocurricular', models.IntegerField()),
            ],
            options={
                'db_table': 'vw_alunos_por_ordem_alfabetica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CadeirasSemestre',
            fields=[
                ('id_unidadecurricular', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('ects', models.IntegerField()),
                ('semestre_id', models.IntegerField()),
                ('semestre_nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Cadeira (2º semestre)',
                'verbose_name_plural': 'Cadeiras (2º semestre)',
                'db_table': 'cadeirassemestre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('grau', models.IntegerField()),
            ],
            options={
                'db_table': 'vw_cursos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('n_turno', models.IntegerField()),
                ('capacidade', models.IntegerField()),
                ('tipo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'vw_turnos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UCMais4Ects',
            fields=[
                ('id_unidadecurricular', models.IntegerField(primary_key=True, serialize=False)),
                ('id_semestre', models.IntegerField()),
                ('id_anocurricular', models.IntegerField()),
                ('ects', models.IntegerField()),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'UC (>4 ECTS)',
                'verbose_name_plural': 'UCs (>4 ECTS)',
                'db_table': 'uc_mais4etcs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwAlunosInscricoes2025',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_inscricao', models.IntegerField()),
                ('data_inscricao', models.DateField()),
                ('n_mecanografico', models.IntegerField()),
                ('aluno_nome', models.CharField(max_length=255)),
                ('aluno_email', models.CharField(max_length=255)),
                ('id_unidadecurricular', models.IntegerField()),
                ('uc_nome', models.CharField(max_length=255)),
                ('id_turno', models.IntegerField()),
            ],
            options={
                'db_table': 'vw_alunos_inscricoes_2025',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwTopDocenteUcAnoCorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_docente', models.IntegerField()),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('total_ucs', models.IntegerField()),
            ],
            options={
                'db_table': 'vw_top_docente_uc_ano_corrente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HorarioPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Horário Oficial', max_length=200)),
                ('ficheiro', models.FileField(upload_to='horarios/')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='aluno',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='anocurricular',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='anoletivo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='docente',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='horario',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='inscricaoturno',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='inscritouc',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='lecionauc',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='matricula',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='semestre',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='turno',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='turnouc',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='unidadecurricular',
            options={'managed': False},
        ),
    ]
