# Generated by Django 5.2.6 on 2026-01-11 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alunosmatriculadospordia_alunosporordemalfabetica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEvento',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('data_hora', models.DateTimeField()),
                ('operacao', models.CharField(max_length=255)),
                ('detalhes', models.TextField()),
                ('utilizador_db', models.CharField(max_length=255)),
                ('chave_primaria', models.CharField(max_length=255)),
                ('entidade', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'log_eventos',
                'ordering': ['-data_hora'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditoriaInscricao',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('data_tentativa', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.CharField(choices=[('sucesso', 'Sucesso'), ('turno_cheio', 'Turno Cheio'), ('conflito_horario', 'Conflito de Horário'), ('nao_autorizado', 'Não Autorizado'), ('uc_duplicada', 'UC Duplicada'), ('erro_sistema', 'Erro do Sistema')], max_length=50)),
                ('motivo_rejeicao', models.TextField(blank=True, null=True)),
                ('tempo_processamento_ms', models.IntegerField(default=0, help_text='Tempo de processamento em millisegundos')),
                ('id_turno', models.ForeignKey(blank=True, db_column='id_turno', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.turno')),
                ('id_unidadecurricular', models.ForeignKey(blank=True, db_column='id_unidadecurricular', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.unidadecurricular')),
                ('n_mecanografico', models.ForeignKey(blank=True, db_column='n_mecanografico', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.aluno')),
            ],
            options={
                'db_table': 'auditoria_inscricao',
                'ordering': ['-data_tentativa'],
                'managed': True,
                'indexes': [models.Index(fields=['n_mecanografico', '-data_tentativa'], name='auditoria_i_n_mecan_a7f742_idx'), models.Index(fields=['resultado'], name='auditoria_i_resulta_8ca880_idx'), models.Index(fields=['data_tentativa'], name='auditoria_i_data_te_f7031c_idx')],
            },
        ),
    ]
