# Generated by Django 5.2.6 on 2026-01-11 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_logevento_horariopdf_id_anocurricular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariopdf',
            name='id_anocurricular',
            field=models.ForeignKey(blank=True, db_column='id_anocurricular', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.anocurricular'),
        ),
        migrations.CreateModel(
            name='AvaliacaoPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Calendário de Avaliações', max_length=200)),
                ('ficheiro', models.FileField(upload_to='avaliacoes/')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_anocurricular', models.ForeignKey(blank=True, db_column='id_anocurricular', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.anocurricular')),
            ],
        ),
    ]
