# Generated by Django 5.2.6 on 2026-01-14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_horariopdf_id_anocurricular_avaliacaopdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="horariopdf",
            name="id_curso",
            field=models.ForeignKey(
                blank=True,
                null=True,
                db_column="id_curso",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.curso",
            ),
        ),
        migrations.AddField(
            model_name="avaliacaopdf",
            name="id_curso",
            field=models.ForeignKey(
                blank=True,
                null=True,
                db_column="id_curso",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.curso",
            ),
        ),
    ]
